name: cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: "21"
          java-distribution: "temurin"
          maven-version: "3.9.6"

      - name: Build with Maven
        run: mvn clean package -Pdeployment --file pom.xml

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>patrimoine-sonic-patrimoine-sonic-repository</id>
                      <username>aws</username>
                      <password>${{ secrets.CODEARTIFACT_AUTH_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Publish package to AWS CodeArtifact
        run: mvn deploy -Pdeployment --settings ~/.m2/settings.xml --file pom.xml