name: cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: '3.9.6'

      - name: Build
        run: mvn clean install
